[mypy]
python_version = 3.11
strict = True
explicit_package_bases = True
warn_unused_ignores = True

plugins =
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = tests.testapp.settings

[mypy-blinker.*]
ignore_missing_imports = True

[mypy-flask.*]
ignore_missing_imports = True

[mypy-flask_sqlalchemy.*]
ignore_missing_imports = True

[mypy-webtest.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

; Monkey-patching modules access internal APIs not exposed by stubs
[mypy-nplusone.ext.sqlalchemy]
disallow_untyped_calls = False

[mypy-nplusone.ext.peewee]
disallow_untyped_calls = False
ignore_errors = True

[mypy-nplusone.ext.flask_sqlalchemy]
disallow_untyped_calls = False
disallow_untyped_decorators = False
