[tox]
env_list = py311, py312, py313, py314, lint, coverage
isolated_build = True

[gh]
python =
    3.11 = py311
    3.12 = py312
    3.13 = py313
    3.14 = py314

[testenv]
allowlist_externals =
    pytest
    py
    python
package = uv
runner = uv-venv-runner
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest {posargs:tests}

[testenv:py311]
dependency_groups = dev, test
basepython = python3.11

[testenv:py312]
dependency_groups = dev, test
basepython = python3.12

[testenv:py313]
dependency_groups = dev, test
basepython = python3.13

[testenv:py314]
dependency_groups = dev, test
basepython = python3.14

[testenv:lint]
allowlist_externals =
    scripts/lint.sh
    scripts/mypy.sh
dependency_groups = dev, lint
commands =
    scripts/lint.sh
    scripts/mypy.sh
    pyright --venvpath {envdir}

[testenv:coverage]
dependency_groups = dev, test
commands =
    pytest --cov-report term-missing --cov-report=xml --cov=nplusone tests

[pytest]
filterwarnings =
    ignore::DeprecationWarning
